#!/usr/bin/python3
import os
import sys
import random
from neuralintents import GenericAssistant

def speak(text):
    os.system(f'flite -t "{text}" -voice slt')

def rick():
    with open("/home/luka/Science/rick.txt", "r") as f:
        rick = f.read().split(";")
    quote = random.choice(rick)
    os.system(f'herbe "{quote}" &')
    speak(quote)

def play_music(i):
    wake_up = "https://www.youtube.com/watch?v=8iVm-AEj2q8&list=PLqyqpQSr8-cYQfLx9U24y303hd8X4VR7A&index=1"
    aggressive = "https://www.youtube.com/watch?v=rf7LrcGQxXQ&list=PLqyqpQSr8-cb5baRWvO4pZg56k1aYOSKP&index=1"
    if "aggressive":
        os.system(f"firefox '{wake_up}'")
        speak("Okay, I'm playing wake up playlist!")
    elif i == 1:
        os.system(f"firefox '{aggressive}'")
        speak("Okay, I'm playing agressive playlist!")
    

mappings = {
        "rick": rick,
        "music": play_music
        }

ai = GenericAssistant("intents.json", model_name="Stella", intent_methods=mappings)
try:
    ai.load_model("/home/luka/Science/Stella")
except Exception:
    ai.train_model()
    ai.save_model("/home/luka/Science/Stella")

ai.request(" ".join(sys.argv[1:]))
